name: generate animated snake

on:
  schedule:
    - cron: "0 */12 * * *" # roda a cada 12 horas
  workflow_dispatch: {} # permite rodar manualmente pela aba Actions
  push:
    branches:
      - main # ajuste se sua branch padrão tiver outro nome

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: MarciaGabrielle
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push snake svg to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
